# Generated by Django 4.2.1 on 2023-08-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Blog_by',
        ),
    ]
